# Generated by Django 4.2.7 on 2023-11-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
