# Generated by Django 4.2.7 on 2023-11-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_note_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
